export interface GearProduct {
  id: string
  name: string
  url: string
  category: string
  description: string
  imagePath?: string
}

export const CATEGORIES = [
  'All',
  'Belay Devices',
  'Harnesses & Helmets',
  'Hardware',
  'Ropes & Rope Bags',
  'Bouldering',
  'Footwear',
  'Nutrition & Hydration',
  'Sun & Skin Care',
  'Tools & Accessories',
  'Camping & Safety',
] as const

export const products: GearProduct[] = [
  {
    id: 'grigri-2',
    name: 'Petzl Grigri 2',
    url: 'https://amzn.to/4aWXbeh',
    category: 'Belay Devices',
    description: 'Compact belay device with assisted-braking for 8.9-10.5mm ropes',
    imagePath: 'petzl-grigri-2.jpg',
  },
  {
    id: 'verso',
    name: 'Petzl Verso',
    url: 'https://amzn.to/45fzDxx',
    category: 'Belay Devices',
    description: 'Lightweight belay device with anti-panic handle for 8.9-10.5mm ropes',
    imagePath: 'petzl-verso.jpg',
  },
  {
    id: 'id-l',
    name: "Petzl I'D L",
    url: 'https://amzn.to/49pEO0r',
    category: 'Belay Devices',
    description: 'Self-braking descender with anti-panic for single ropes 8.9-10.5mm',
    imagePath: 'petzl-id-l.jpg',
  },
  {
    id: 'reverso',
    name: 'Petzl Reverso',
    url: 'https://amzn.to/45ijYO6',
    category: 'Belay Devices',
    description: 'Versatile belay device for lead climbing and rappelling',
    imagePath: 'petzl-reverso.jpg',
  },
  {
    id: 'vertex-vent',
    name: 'Petzl Vertex Vent',
    url: 'https://amzn.to/49zEjQc',
    category: 'Harnesses & Helmets',
    description: 'Lightweight ventilated climbing helmet with adjustable fit',
    imagePath: 'petzl-vertex-vent.jpg',
  },
  {
    id: 'corax-harness',
    name: 'Petzl Corax',
    url: 'https://amzn.to/4qzkY91',
    category: 'Harnesses & Helmets',
    description: 'Adjustable all-around climbing harness for sport and trad',
    imagePath: 'petzl-corax-harness.jpg',
  },
  {
    id: 'smd-carabiner',
    name: "Petzl SM'D",
    url: 'https://amzn.to/4qUzGHp',
    category: 'Hardware',
    description: 'Compact asymmetrical D-carabiner with screwgate for quickdraws',
    imagePath: 'petzl-smd-carabiner.jpg',
  },
  {
    id: 'micro-traxion',
    name: 'Petzl Micro Traxion',
    url: 'https://amzn.to/4sOgxca',
    category: 'Hardware',
    description: 'Compact rope clamp with pulley for rescue and hauling',
    imagePath: 'petzl-micro-traxion.jpg',
  },
  {
    id: 'conga-8',
    name: 'Petzl Conga 8.0',
    url: 'https://amzn.to/49GtbAW',
    category: 'Hardware',
    description: 'Ultra-light cordelette pulley for progression systems',
    imagePath: 'petzl-conga-8.jpg',
  },
  {
    id: 'spirit-express',
    name: 'Petzl Spirit Express',
    url: 'https://amzn.to/4sK5uR8',
    category: 'Hardware',
    description: 'Lightweight quickdraw with Express clips for sport climbing',
    imagePath: 'petzl-spirit-express.jpg',
  },
  {
    id: 'ouistiti',
    name: 'Petzl Ouistiti',
    url: 'https://amzn.to/3Li2qef',
    category: 'Hardware',
    description: 'Compact belay device designed for children and beginners',
    imagePath: 'petzl-ouistiti.jpg',
  },
  {
    id: 'rope-9-2mm',
    name: 'Petzl 9.2mm X 30m',
    url: 'https://amzn.to/4sJ7WY3',
    category: 'Ropes & Rope Bags',
    description: 'Ultra-lightweight single rope for gym and indoor climbing',
    imagePath: 'petzl-rope-9-2mm.jpg',
  },
  {
    id: 'psychibag',
    name: 'Psychi Rope Bag',
    url: 'https://amzn.to/3Nq2UQ0',
    category: 'Ropes & Rope Bags',
    description: 'Compact rope bag with tarp for easy rope management',
    imagePath: 'psychibag.jpg',
  },
  {
    id: 'bug-pack',
    name: 'Petzl Bug',
    url: 'https://amzn.to/4qrc3qd',
    category: 'Ropes & Rope Bags',
    description: 'Lightweight pack with rope tarp for approaches and cragging',
    imagePath: 'petzl-bug.jpg',
  },
  {
    id: 'tarp',
    name: 'Petzl Tarp',
    url: 'https://amzn.to/45VukU6',
    category: 'Ropes & Rope Bags',
    description: 'Compact tarp for rope protection and gear organization',
    imagePath: 'petzl-tarp.jpg',
  },
  {
    id: 'circuit-crashpad',
    name: 'Black Diamond Circuit',
    url: 'https://amzn.to/3LKTyOi',
    category: 'Bouldering',
    description: 'Ultralight crash pad with carrying system for bouldering',
    imagePath: 'black-diamond-circuit.jpg',
  },
  {
    id: 'liquid-chalk',
    name: 'NOVU Liquid Chalk',
    url: 'https://amzn.to/3NpbWwH',
    category: 'Bouldering',
    description: 'Liquid chalk for superior grip in climbing and fitness',
    imagePath: 'novu-liquid-chalk.jpg',
  },
  {
    id: 'chalk-block',
    name: 'Firstaid4sport Chalk Block',
    url: 'https://amzn.to/45htbGh',
    category: 'Bouldering',
    description: 'Professional chalk block for enhanced grip and friction',
    imagePath: 'firstaid4sport-chalk.jpg',
  },
  {
    id: 'climbing-brush',
    name: 'Madu Climb Brush',
    url: 'https://amzn.to/3LIm9DM',
    category: 'Bouldering',
    description: "Boar's hair brush with built-in skin file for holds",
    imagePath: 'madu-brush.jpg',
  },
  {
    id: 'tarantula',
    name: 'La Sportiva Tarantula',
    url: 'https://amzn.to/4r1lNrc',
    category: 'Footwear',
    description: 'Beginner-friendly climbing shoes with comfortable fit',
    imagePath: 'la-sportiva-tarantula.jpg',
  },
  {
    id: 'tx4-evo',
    name: 'La Sportiva TX4 Evo GTX',
    url: 'https://amzn.to/4qWlcXC',
    category: 'Footwear',
    description: 'Gore-Tex approach shoes for technical terrain and climbing',
    imagePath: 'la-sportiva-tx4.jpg',
  },
  {
    id: 'thermos-470ml',
    name: 'Thermos Stainless King (470ml)',
    url: 'https://amzn.to/49nZ82a',
    category: 'Nutrition & Hydration',
    description: 'Stainless steel food flask keeps meals hot for 9 hours',
    imagePath: 'thermos-470ml.jpg',
  },
  {
    id: 'thermos-1-2l',
    name: 'Thermos Midnight Blue (1.2L)',
    url: 'https://amzn.to/3Ze1Y3I',
    category: 'Nutrition & Hydration',
    description: 'Large capacity travel flask keeps drinks hot for 24 hours',
    imagePath: 'thermos-1-2l.jpg',
  },
  {
    id: 'protein-bars',
    name: 'Nature Valley Protein Bars',
    url: 'https://amzn.to/4bluAzF',
    category: 'Nutrition & Hydration',
    description: 'Peanut and chocolate protein cereal bars, gluten-free',
    imagePath: 'nature-valley-bars.jpg',
  },
  {
    id: 'protein-bar-grenade',
    name: 'Grenade OREO Protein Bar',
    url: 'https://amzn.to/4pDwvTl',
    category: 'Nutrition & Hydration',
    description: 'High protein, low sugar protein bar with Oreo flavor',
    imagePath: 'grenade-protein-bar.jpg',
  },
  {
    id: 'nakd-bars',
    name: 'Nakd Fruit & Nut Bar Variety',
    url: 'https://amzn.to/3NwZ87n',
    category: 'Nutrition & Hydration',
    description: 'Vegan, gluten-free fruit and nut snack bars',
    imagePath: 'nakd-bars.jpg',
  },
  {
    id: 'sunscreen',
    name: 'La Roche-Posay Anthelios SPF50+',
    url: 'https://amzn.to/4qrbSLz',
    category: 'Sun & Skin Care',
    description: 'Invisible fluid sunscreen for sensitive skin, SPF50+',
    imagePath: 'la-roche-posay-sunscreen.jpg',
  },
  {
    id: 'vaseline',
    name: 'Vaseline Petroleum Jelly',
    url: 'https://amzn.to/4pDbg47',
    category: 'Sun & Skin Care',
    description: 'Original pure petroleum jelly for dry skin protection',
    imagePath: 'vaseline.jpg',
  },
  {
    id: 'cerave',
    name: 'CeraVe Moisturizing Cream',
    url: 'https://amzn.to/3NwZ2g1',
    category: 'Sun & Skin Care',
    description: 'Face and body cream with ceramides and hyaluronic acid',
    imagePath: 'cerave.jpg',
  },
  {
    id: 'tacvasen-hoodie',
    name: 'TACVASEN Hoodie',
    url: 'https://amzn.to/3LONbJN',
    category: 'Sun & Skin Care',
    description: 'UPF 50+ sun protection long sleeve quick dry outdoor hoodie',
    imagePath: 'tacvasen-hoodie.jpg',
  },
  {
    id: 'clipstick',
    name: 'Beta Stick EVO',
    url: 'https://amzn.to/45htsch',
    category: 'Tools & Accessories',
    description: 'Extendable clipstick for clipping bolts and quickdraws',
    imagePath: 'beta-stick-evo.jpg',
  },
  {
    id: 'cordex-gloves',
    name: 'Petzl Cordex Plus',
    url: 'https://amzn.to/4q12SMh',
    category: 'Tools & Accessories',
    description: 'Reinforced belay gloves for durability and grip',
    imagePath: 'petzl-cordex-gloves.jpg',
  },
  {
    id: 'belay-glasses',
    name: 'BG Climbing Belay Glasses',
    url: 'https://amzn.to/3YHWr5u',
    category: 'Tools & Accessories',
    description: 'Ergonomic belay glasses for comfortable spotting',
    imagePath: 'belay-glasses.jpg',
  },
  {
    id: 'walkie-talkie',
    name: 'Retevis RT24',
    url: 'https://amzn.to/49zFlvy',
    category: 'Tools & Accessories',
    description: 'License-free PMR446 two-way radio for outdoor communication',
    imagePath: 'retevis-rt24.jpg',
  },
  {
    id: 'first-aid-kit',
    name: 'First Aid Kit (130 Pieces)',
    url: 'https://amzn.to/49CNa3A',
    category: 'Camping & Safety',
    description: 'Complete first aid kit with emergency blanket and supplies',
    imagePath: 'first-aid-kit.jpg',
  },
  {
    id: 'jetboil',
    name: 'Jetboil Flash 1.0L',
    url: 'https://amzn.to/3NwZhHX',
    category: 'Camping & Safety',
    description: 'Fast boil stove system for camping and backpacking',
    imagePath: 'jetboil-flash.jpg',
  },
  {
    id: 'camping-chair',
    name: 'EVER ADVANCED Camping Chair',
    url: 'https://amzn.to/3ZlyG3b',
    category: 'Camping & Safety',
    description: 'Oversized camping chair supporting up to 230kg',
    imagePath: 'ever-advanced-chair.jpg',
  },
]
