export interface GearProduct {
  id: string
  name: string
  url: string
  category: string
  description: string
  imagePath?: string
  imageUrl?: string
}

export const CATEGORIES = [
  'All',
  'Belay Devices',
  'Harnesses & Helmets',
  'Hardware',
  'Ropes & Rope Bags',
  'Bouldering',
  'Footwear',
  'Nutrition & Hydration',
  'Sun & Skin Care',
  'Tools & Accessories',
  'Camping & Safety',
] as const

export const products: GearProduct[] = [
  {
    id: 'grigri-2',
    name: 'Petzl Grigri 2 Belay Device',
    url: 'https://amzn.to/4aWXbeh',
    category: 'Belay Devices',
    description: 'Compact belay device with assisted-braking for 8.9-10.5mm ropes',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Grigri%202.jpg',
  },
  {
    id: 'verso',
    name: 'Petzl Verso Belay Device',
    url: 'https://amzn.to/45fzDxx',
    category: 'Belay Devices',
    description: 'Lightweight belay device with anti-panic handle for 8.9-10.5mm ropes',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/petzl-verso.jpg',
  },
  {
    id: 'id-l',
    name: "Petzl I'D L Descender",
    url: 'https://amzn.to/49pEO0r',
    category: 'Belay Devices',
    description: 'Self-braking descender with anti-panic for single ropes 8.9-10.5mm',
    imageUrl: `https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Unisex's%20I'D%20L%20Descender.jpg`,
  },
  {
    id: 'reverso',
    name: 'Petzl Reverso Belay Device',
    url: 'https://amzn.to/45ijYO6',
    category: 'Belay Devices',
    description: 'Versatile belay device for lead climbing and rappelling',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/petzl-reverso.jpg',
  },
  {
    id: 'vertex-vent',
    name: 'Petzl Vertex Vent Helmet',
    url: 'https://amzn.to/49zEjQc',
    category: 'Harnesses & Helmets',
    description: 'Lightweight ventilated climbing helmet with adjustable fit',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Vertex%20Vent.jpg',
  },
  {
    id: 'corax-harness',
    name: 'Petzl Corax Harness',
    url: 'https://amzn.to/4qzkY91',
    category: 'Harnesses & Helmets',
    description: 'Adjustable all-around climbing harness for sport and trad',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Unisex%20Corax%20Harness%20For%20Climbing.jpg',
  },
  {
    id: 'smd-carabiner',
    name: "Petzl SM'D Carabiner",
    url: 'https://amzn.to/4qUzGHp',
    category: 'Hardware',
    description: 'Compact asymmetrical D-carabiner with screwgate for quickdraws',
    imageUrl: `https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/SM'D%20Carabiner.jpg`,
  },
  {
    id: 'micro-traxion',
    name: 'Petzl Micro Traxion Pulley',
    url: 'https://amzn.to/4sOgxca',
    category: 'Hardware',
    description: 'Compact rope clamp with pulley for rescue and hauling',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/microtraxion.jpg',
  },
  {
    id: 'conga-8',
    name: 'Petzl Conga 8.0 Pulley',
    url: 'https://amzn.to/49GtbAW',
    category: 'Hardware',
    description: 'Ultra-light cordelette pulley for progression systems',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/petzl%20Conga%208.0%20mm.jpg',
  },
  {
    id: 'spirit-express',
    name: 'Petzl Spirit Express Quickdraw',
    url: 'https://amzn.to/4sK5uR8',
    category: 'Hardware',
    description: 'Lightweight quickdraw with Express clips for sport climbing',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%2C%20Spirit%20Express%2C%20Light%20And%20Multipurpose%20Postp.jpg',
  },
  {
    id: 'ouistiti',
    name: 'Petzl Ouistiti Belay Device',
    url: 'https://amzn.to/3Li2qef',
    category: 'Hardware',
    description: 'Compact belay device designed for children and beginners',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Ouistiti.jpg',
  },
  {
    id: 'rope-9-2mm',
    name: 'Petzl 9.2mm x 30m Rope',
    url: 'https://amzn.to/4sJ7WY3',
    category: 'Ropes & Rope Bags',
    description: 'Ultra-lightweight single rope for gym and indoor climbing',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Unisex%209.2%20Mm%20X%2030%20M.jpg',
  },
  {
    id: 'psychibag',
    name: 'Psychi Rope Bag',
    url: 'https://amzn.to/3Nq2UQ0',
    category: 'Ropes & Rope Bags',
    description: 'Compact rope bag with tarp for easy rope management',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Psychi%20Rock%20Climbing%20Rope%20Bag.jpg',
  },
  {
    id: 'bug-pack',
    name: 'Petzl Bug Pack',
    url: 'https://amzn.to/4qrc3qd',
    category: 'Ropes & Rope Bags',
    description: 'Lightweight pack with rope tarp for approaches and cragging',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Petzl%20Erwachsene%20Rucksack%20Bug.jpg',
  },
  {
    id: 'tarp',
    name: 'Petzl Tarp',
    url: 'https://amzn.to/45VukU6',
    category: 'Ropes & Rope Bags',
    description: 'Compact tarp for rope protection and gear organization',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%2C%20Tarp%2C%20Rope%20Holder%20Towel%2C%20Black%2C%20One%20Size%2C%20Unisex-Adult.jpg',
  },
  {
    id: 'circuit-crashpad',
    name: 'Black Diamond Circuit Crash Pad',
    url: 'https://amzn.to/3LKTyOi',
    category: 'Bouldering',
    description: 'Ultralight crash pad with carrying system for bouldering',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/BLACK%20DIAMOND%20Circuit%20Crash%20Pad%20for%20Boulder%20and%20Rock%20Climbing.jpg',
  },
  {
    id: 'liquid-chalk',
    name: 'NOVU Liquid Chalk',
    url: 'https://amzn.to/3NpbWwH',
    category: 'Bouldering',
    description: 'Liquid chalk for superior grip in climbing and fitness',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/NOVU%20Fitness%20-%20Liquid%20Chalk%20for%20Superior%20Grip%20-%20Weightlifting%2C%20Climbing%2C%20Fitness.jpg',
  },
  {
    id: 'chalk-block',
    name: 'Firstaid4sport Chalk Block',
    url: 'https://amzn.to/45htbGh',
    category: 'Bouldering',
    description: 'Professional chalk block for enhanced grip and friction',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Firstaid4sport%20Professional%202oz.jpg',
  },
  {
    id: 'climbing-brush',
    name: 'Madu Climb Brush',
    url: 'https://amzn.to/3LIm9DM',
    category: 'Bouldering',
    description: "Boar's hair brush with built-in skin file for holds",
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Madu%20Rock%20Climbing%20Brush.jpg',
  },
  {
    id: 'tarantula',
    name: 'La Sportiva Tarantula Shoes',
    url: 'https://amzn.to/4r1lNrc',
    category: 'Footwear',
    description: 'Beginner-friendly climbing shoes with comfortable fit',
    imageUrl: `https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Boulder%20Tarantula%2C%20Men's%20Climbing%20Shoes.jpg`,
  },
  {
    id: 'tx4-evo',
    name: 'La Sportiva TX4 Evo GTX',
    url: 'https://amzn.to/4qWlcXC',
    category: 'Footwear',
    description: 'Gore-Tex approach shoes for technical terrain and climbing',
    imageUrl: `https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/A%20SPORTIVA%20TX4%20Evo%20GTX%20-%20Men's%20Approach%20Shoes.jpg`,
  },
  {
    id: 'thermos-470ml',
    name: 'Thermos 470ml Flask',
    url: 'https://amzn.to/49nZ82a',
    category: 'Nutrition & Hydration',
    description: 'Stainless steel food flask keeps meals hot for 9 hours',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Thermos%20470ml.jpg',
  },
  {
    id: 'thermos-1-2l',
    name: 'Thermos 1.2L Flask',
    url: 'https://amzn.to/3Ze1Y3I',
    category: 'Nutrition & Hydration',
    description: 'Large capacity travel flask keeps drinks hot for 24 hours',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Thermos%201.2L.jpg',
  },
  {
    id: 'protein-bars',
    name: 'Nature Valley Protein Bars',
    url: 'https://amzn.to/4bluAzF',
    category: 'Nutrition & Hydration',
    description: 'Peanut and chocolate protein cereal bars, gluten-free',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Nature%20Valley%20Protein%20Peanut%20%26%20Chocolate%20Gluten%20Free%20C.jpg',
  },
  {
    id: 'protein-bar-grenade',
    name: 'Grenade OREO Protein Bar',
    url: 'https://amzn.to/4pDwvTl',
    category: 'Nutrition & Hydration',
    description: 'High protein, low sugar protein bar with Oreo flavor',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/grenade%20OREO%20White%20Protein%20Bar%20-%20High%20Protein%2C.jpg',
  },
  {
    id: 'nakd-bars',
    name: 'Nakd Fruit & Nut Bars',
    url: 'https://amzn.to/3NwZ87n',
    category: 'Nutrition & Hydration',
    description: 'Vegan, gluten-free fruit and nut snack bars',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Nakd%20Fruit%20%26%20Nut%20Bar%20Variety%20Pack%20-%20Vegan%20-%20.jpg',
  },
  {
    id: 'sunscreen',
    name: 'La Roche-Posay SPF50+ Sunscreen',
    url: 'https://amzn.to/4qrbSLz',
    category: 'Sun & Skin Care',
    description: 'Invisible fluid sunscreen for sensitive skin, SPF50+',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Roche-Posay%20Anthelios%20UVMune%20400%20Ultra-Light%20Invisible%20.jpg',
  },
  {
    id: 'vaseline',
    name: 'Vaseline Petroleum Jelly',
    url: 'https://amzn.to/4pDbg47',
    category: 'Sun & Skin Care',
    description: 'Original pure petroleum jelly for dry skin protection',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/aseline%20Original%20Pure%20Petroleum%20Jell.jpg',
  },
  {
    id: 'cerave',
    name: 'CeraVe Moisturizing Cream',
    url: 'https://amzn.to/3NwZ2g1',
    category: 'Sun & Skin Care',
    description: 'Face and body cream with ceramides and hyaluronic acid',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/CeraVe%20Moisturising%20Cream%2C%20Face%20%26%20Body%2C%20With%203%20essentia.jpg',
  },
  {
    id: 'tacvasen-hoodie',
    name: 'TACVASEN UPF50+ Hoodie',
    url: 'https://amzn.to/3LONbJN',
    category: 'Sun & Skin Care',
    description: 'UPF 50+ sun protection long sleeve quick dry outdoor hoodie',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/TACVASEN%20Men%27s%20Hoodies%20UPF%2050%2B%20Sun%20Protection%20Performance.jpg',
  },
  {
    id: 'clipstick',
    name: 'Beta Stick EVO Clipstick',
    url: 'https://amzn.to/45htsch',
    category: 'Tools & Accessories',
    description: 'Extendable clipstick for clipping bolts and quickdraws',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Clipstick.jpg',
  },
  {
    id: 'cordex-gloves',
    name: 'Petzl Cordex Plus Gloves',
    url: 'https://amzn.to/4q12SMh',
    category: 'Tools & Accessories',
    description: 'Reinforced belay gloves for durability and grip',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Cordex%20Plus%20Gloves%20for%20Adults.jpg',
  },
  {
    id: 'belay-glasses',
    name: 'BG Climbing Belay Glasses',
    url: 'https://amzn.to/3YHWr5u',
    category: 'Tools & Accessories',
    description: 'Ergonomic belay glasses for comfortable spotting',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/BG-Climbing-Belay-Glasses-Rock.jpg',
  },
  {
    id: 'walkie-talkie',
    name: 'Retevis RT24 Walkie Talkie',
    url: 'https://amzn.to/49zFlvy',
    category: 'Tools & Accessories',
    description: 'License-free PMR446 two-way radio for outdoor communication',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/etevis%20RT24%20Walkie%20Talkie%20PMR446%20License-free%20Prof.jpg',
  },
  {
    id: 'first-aid-kit',
    name: 'First Aid Kit (130pc)',
    url: 'https://amzn.to/49CNa3A',
    category: 'Camping & Safety',
    description: 'Complete first aid kit with emergency blanket and supplies',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/130%20Pieces%20First%20Aid%20Kit%20with%20Hospital%20Grade%20Medical%20Supplies%20-%20.jpg',
  },
  {
    id: 'jetboil',
    name: 'Jetboil Flash 1.0L',
    url: 'https://amzn.to/3NwZhHX',
    category: 'Camping & Safety',
    description: 'Fast boil stove system for camping and backpacking',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/etboil%20Flash%201.0L%20Portable%20Fast%20Boil%20Stov.jpg',
  },
  {
    id: 'camping-chair',
    name: 'EVER ADVANCED Camping Chair',
    url: 'https://amzn.to/3ZlyG3b',
    category: 'Camping & Safety',
    description: 'Oversized camping chair supporting up to 230kg',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/EVER%20ADVANCED%20Camping%20Chair%20for%20Adults%20Oversized%20230KG.jpg',
  },
  {
    id: 'dragonfly-micro-cams',
    name: 'DMM Dragonfly Micro Cams',
    url: 'https://amzn.to/4pEaaoJ',
    category: 'Hardware',
    description: 'Micro cams for thin cracks and delicate placements',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Dmm%20Dragonfly%20Micro%20Cams.jpg',
  },
  {
    id: 'camp-nano-22',
    name: 'CAMP Nano 22 Cam',
    url: 'https://amzn.to/4qZwgDm',
    category: 'Hardware',
    description: 'Compact cam with thumb trigger for precision placements',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/CAMP%20Nano%2022.jpg',
  },
  {
    id: 'dmm-dragon-cam',
    name: 'DMM Dragon Cam',
    url: 'https://amzn.to/4sD6eY6',
    category: 'Hardware',
    description: 'Reliable caming unit with double axle design',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/DMM%20Dragon%20Cam.jpg',
  },
  {
    id: 'sporttape-finger-tape',
    name: 'SPORTTAPE Finger Tape',
    url: 'https://amzn.to/4q4jKBP',
    category: 'Tools & Accessories',
    description: 'Essential finger tape for crack climbing',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/SPORTTAPE%202%20Rolls%20(20m)%20Zinc%20Oxide%20Finger%20Tape.jpg',
  },
  {
    id: 'connect-adjust-self-single',
    name: 'CONNECT ADJUST Quickdraw',
    url: 'https://amzn.to/3YO1eCn',
    category: 'Hardware',
    description: 'Adjustable quickdraw for varied lengths',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/CONNECT%20ADJUST%20-%20REGULABLE%20SELF%20SINGLE.jpg',
  },
  {
    id: 'mammut-tubular-sling',
    name: 'Mammut Tubular Sling 80cm',
    url: 'https://amzn.to/49Ga6in',
    category: 'Hardware',
    description: 'Durable sewn sling for anchors and quickdraws',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Mammut%20Tubular%20Sling%2016.0%2080cm%2080%20cm.jpg',
  },
  {
    id: 'black-diamond-camalot-c4',
    name: 'Black Diamond Camalot C4',
    url: 'https://amzn.to/4sKVE1n',
    category: 'Hardware',
    description: 'Industry-standard cam with double-axle design',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Black%20Diamond%20Camalot%20C4%2C%203.jpg',
  },
  {
    id: 'gramicci-japan-pants-olive',
    name: 'Gramicci Japan Pants',
    url: 'https://amzn.to/4a1CFrY',
    category: 'Camping & Safety',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Gramicci%20Japan%20Gramicci%20Pants%20-%20Olive.jpg',
  },
  {
    id: 'moko-chalk-bag',
    name: 'MoKo Chalk Bag',
    url: 'https://amzn.to/3NrbpdD',
    category: 'Bouldering',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/MoKo%20Chalk%20Bag%2C%20Drawstring%20Rock%20Climbing%20Chalk%20Bag%20Bouldering%20Chalk%20Bag%20Bucket.jpg',
  },
  {
    id: 'stanley-flip-straw-water-bottle',
    name: 'Stanley Water Bottle',
    url: 'https://amzn.to/45m09p7',
    category: 'Nutrition & Hydration',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Stanley%201913%20Flip%20Straw%202.0%20Sports%20Water%20Bottle%20with%20Straw%200.7L.jpg',
  },
  {
    id: 'north-face-thermoball-snow-boots',
    name: 'North Face Thermoball Boots',
    url: 'https://amzn.to/4pJ1hKR',
    category: 'Footwear',
    description: '',
    imageUrl: `https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/THE%20NORTH%20FACE%20Men's%20Thermoball%20Traction%20Snow%20Boots%20.jpg`,
  },
  {
    id: 'rab-cirrus-hut-slippers',
    name: 'Rab Cirrus Hut Slippers',
    url: 'https://amzn.to/49LNnSf',
    category: 'Camping & Safety',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Rab%20Cirrus%20Hut%20Slippers.jpg',
  },
  {
    id: 'beemat-widdop-crash-pad',
    name: 'BEEMAT Widdop Crash Pad',
    url: 'https://amzn.to/4qDnZW4',
    category: 'Bouldering',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/BEEMAT%20Widdop%20Bouldering%20Crash%20Pad.jpg',
  },
  {
    id: 'sheep-rock-chalk-bag',
    name: 'Sheep Rock Chalk Bag',
    url: 'https://amzn.to/49ZSIXf',
    category: 'Bouldering',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Sheep%20Rock%20Climbing%20Chalk%20Bag.jpg',
  },
  {
    id: 'mini-wooden-climbing-device',
    name: 'Mini Wooden Climbing Board',
    url: 'https://amzn.to/4qtrLkp',
    category: 'Tools & Accessories',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Mini%20Wooden%20Climbing%20Device%20.jpg',
  },
  {
    id: 'baguette-evo-hangboard',
    name: 'Baguette Evo Hangboard',
    url: 'https://amzn.to/4pOtwrp',
    category: 'Tools & Accessories',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Baguette%20Evo%20Climbing%20hangboard.jpg',
  },
  {
    id: 'yy-hangboard',
    name: 'YY Hangboard',
    url: 'https://amzn.to/4a8RKHh',
    category: 'Tools & Accessories',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/YY%20Hangboard.jpg',
  },
  {
    id: 'two-stones-mug',
    name: 'Two Stones Mug',
    url: 'https://amzn.to/4pJUmRr',
    category: 'Nutrition & Hydration',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Two%20Stones%20Mug.jpg',
  },
  {
    id: 'chalk-bag-bucket-bundle',
    name: 'Chalk Bag Bundle',
    url: 'https://amzn.to/4r1Y0ak',
    category: 'Bouldering',
    description: '',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Chalk%20Bag%20Bucket%20Bundle.jpg',
  },
  {
    id: 'mammut-crag-dry-rope-9-5mm',
    name: 'Mammut Crag Dry Rope 9.5mm',
    url: 'https://amzn.to/3ZnSEdL',
    category: 'Ropes & Rope Bags',
    description: 'Durable dry-treated climbing rope with diameter optimized for versatile use',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Mammut%20Crag%20Dry%20Rope%209%2C5%20mm.jpg',
  },
  {
    id: 'beal-karma-rope-9-8mm',
    name: 'Beal Karma 9.8mm Rope',
    url: 'https://amzn.to/3Ny2aZa',
    category: 'Ropes & Rope Bags',
    description: 'Versatile single rope with Golden Dry treatment for excellent durability',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Beal%209.8mm%20Karma%20Climbing%20Rope%2C%20Red%2C%20One%20Size%20.jpg',
  },
  {
    id: 'beal-rando-rope-8mm-30m',
    name: 'Beal Rando 8mm x 30m Rope',
    url: 'https://amzn.to/49Oegov',
    category: 'Ropes & Rope Bags',
    description: 'Lightweight double/twin/half rope for alpine and glacier travel',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Beal%20Rando%20Double%20%26%20Twin%20%26%20Half%20Ropes%208%20mm%20x%2030%20m%20.jpg',
  },
  {
    id: 'edelrid-on-sight-rope-9-8mm',
    name: 'EDELRID On Sight 9.8mm Rope',
    url: 'https://amzn.to/49Oegov',
    category: 'Ropes & Rope Bags',
    description: 'High-performance single rope with Shield treatment for maximum durability',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/EDELRID%20On%20Sight%20Climbing%20Rope%209.8%20mm.jpg',
  },
  {
    id: 'edelrid-boa-rope-9-8mm',
    name: 'EDELRID Boa 9.8mm Rope',
    url: 'https://amzn.to/4qtyGdr',
    category: 'Ropes & Rope Bags',
    description: 'Versatile climbing rope with excellent grip and durability',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/EDELRID%20Climbing%20Ropes%20Boa%209%2C8%20.jpg',
  },
  {
    id: 'black-diamond-quickdraws',
    name: 'Black Diamond Quickdraws',
    url: 'https://amzn.to/4pNYq2Y',
    category: 'Hardware',
    description: 'Durable quickdraws for sport climbing with dogbone protectors',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Black%20Diamond%20Quickdraws.jpg',
  },
  {
    id: 'edelrid-express-set-bulletproof',
    name: 'EDELRID Express Set Bulletproof',
    url: 'https://amzn.to/464WsnT',
    category: 'Hardware',
    description: 'Heavy-duty express set with rubber retainer for snag-free clipping',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/EDELRID%20Express%20Set%20Bulletproof%20.jpg',
  },
  {
    id: 'petzl-meteor-helmet',
    name: 'Petzl Meteor Helmet',
    url: 'https://amzn.to/4sPhKj5',
    category: 'Harnesses & Helmets',
    description: 'Lightweight and ventilated helmet for climbing and mountaineering',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Unisex%20Adult%20Meteor%20Helmet%20.jpg',
  },
  {
    id: 'black-diamond-half-dome-helmet',
    name: 'Black Diamond Half Dome Helmet',
    url: 'https://amzn.to/4a6FxUs',
    category: 'Harnesses & Helmets',
    description: 'Classic climbing helmet with reliable protection and ventilation',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Black%20Diamond%20Half%20Dome%20Helmet%20.jpg',
  },
  {
    id: 'petzl-sirocco-helmet',
    name: 'Petzl Sirocco Helmet',
    url: 'https://amzn.to/49yvIyy',
    category: 'Harnesses & Helmets',
    description: 'Ultra-lightweight helmet for climbing and mountain activities',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Petzl%20Sirocco%20Helmet%2053-61%20cm%20.jpg',
  },
  {
    id: 'mammut-4-slide-harness',
    name: 'Mammut 4 Slide Harness',
    url: 'https://amzn.to/3LSkT17',
    category: 'Harnesses & Helmets',
    description: 'Adjustable all-round harness for climbing and mountaineering',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Mammut%204%20Slide%20Harness%20Harnesses%20.jpg',
  },
  {
    id: 'black-diamond-solution-harness',
    name: 'Black Diamond Solution Harness',
    url: 'https://amzn.to/3ZmjoLA',
    category: 'Harnesses & Helmets',
    description: 'Lightweight sport climbing harness with Infinity loop',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Black%20Diamond%20Solution.jpg',
  },
  {
    id: 'la-sportiva-skwama',
    name: 'La Sportiva Skwama Shoes',
    url: 'https://amzn.to/4pSp2jI',
    category: 'Footwear',
    description: 'High-performance slipper-style climbing shoe with S-Heel technology',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Skwama.jpg',
  },
  {
    id: 'la-sportiva-finale',
    name: 'La Sportiva Finale Shoes',
    url: 'https://amzn.to/4bFXlXF',
    category: 'Footwear',
    description: 'Versatile climbing shoe ideal for all-day comfort and performance',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Finale.jpg',
  },
  {
    id: 'la-sportiva-katana-lace',
    name: 'La Sportiva Katana Lace Shoes',
    url: 'https://amzn.to/3LY54WH',
    category: 'Footwear',
    description: 'Precision lace-up shoe with excellent sensitivity and support',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Katana%20Lace.jpg',
  },
  {
    id: 'la-sportiva-solution-comp',
    name: 'La Sportiva Solution Comp',
    url: 'https://amzn.to/45jclXM',
    category: 'Footwear',
    description: 'Competition-focused shoe with aggressive downturn and locking strap',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Solution%20Comp.jpg',
  },
  {
    id: 'petzl-neox',
    name: 'Petzl Neox Belay Device',
    url: 'https://amzn.to/3NWV9Bc',
    category: 'Belay Devices',
    description: 'Assisted-braking belay device with anti-panic handle for 8.9-10.5mm ropes',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/PETZL%20Neox%20Belay%20Device.jpg',
  },
  {
    id: 'scarpa-instinct-vs',
    name: 'Scarpa Instinct VS',
    url: 'https://amzn.to/4jWHq9G',
    category: 'Footwear',
    description: 'High-performance aggressive climbing shoe with Microsuede upper',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Scarpa%20Instinct%20VS.jpg',
  },
  {
    id: 'la-sportiva-skwama-womens',
    name: 'La Sportiva Skwama - Women\'s',
    url: 'https://amzn.to/49BQMEh',
    category: 'Footwear',
    description: 'Women\'s high-performance slipper-style climbing shoe with S-Heel technology',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Skwama%20-%20Women%27s%20.jpg',
  },
  {
    id: 'la-sportiva-katana-lace-womens',
    name: 'La Sportiva Katana Lace - Women\'s',
    url: 'https://amzn.to/3ZtjqRX',
    category: 'Footwear',
    description: 'Women\'s precision lace-up shoe with excellent sensitivity and support',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Katana%20Lace%20-%20Women%27s%20.jpg',
  },
  {
    id: 'evolv-venega',
    name: 'Evolv Venga',
    url: 'https://amzn.to/4pVu3Ig',
    category: 'Footwear',
    description: 'Versatile climbing shoe with aggressive downturn for all-day performance',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Evolv%20Kids%20Venga%20Climbing%20Shoe.jpg',
  },
  {
    id: 'la-sportiva-tx-guide',
    name: 'La Sportiva TX Guide',
    url: 'https://amzn.to/49QZPzR',
    category: 'Footwear',
    description: 'Technical approach shoe with durable rubber sole for mountain approaches',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20TX%20Guide%20.jpg',
  },
  {
    id: 'scarpa-crux',
    name: 'Scarpa Crux Shoe',
    url: 'https://amzn.to/4pYx1vsm',
    category: 'Footwear',
    description: 'Performance climbing shoe with precision toe patch and supportive heel',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Scarpa%20Crux%20Shoe.jpg',
  },
  {
    id: 'la-sportiva-boulder-x',
    name: 'La Sportiva Boulder X Shoe',
    url: 'https://amzn.to/4byDgmn',
    category: 'Footwear',
    description: 'Durable bouldering shoe with sticky rubber and comfortable fit',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/La%20Sportiva%20Boulder%20X%20shoe.jpg',
  },
  {
    id: 'petzl-sitta',
    name: 'Petzl Sitta',
    url: 'https://amzn.to/3Zsig9h',
    category: 'Harnesses & Helmets',
    description: 'Ultra-lightweight harness for sport climbing and alpine adventures',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Petzl%20Sitta%20.jpg',
  },
  {
    id: 'petzl-sama',
    name: 'Petzl Sama',
    url: 'https://amzn.to/3Nz2xCQ',
    category: 'Harnesses & Helmets',
    description: 'Lightweight women\'s harness for sport climbing and gym climbing',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Petzl%20Sama%20.jpg',
  },
  {
    id: 'petzl-macchu',
    name: 'PETZL Macchu',
    url: 'https://amzn.to/4qCI4f1',
    category: 'Harnesses & Helmets',
    description: 'Women\'s ultra-light harness designed for technical alpine climbing',
    imageUrl: 'https://glxnbxbkedeogtcivpsx.supabase.co/storage/v1/object/public/Gear%20Images/Petzl%20Macchu%20.jpg',
  },
]
